name: football-data

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

permissions: write-all

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests selenium pandas

      - name: Run script
        run: |
          python scrapper.py

      - name: Update date.json
        uses: test-room-7/action-update-file@v1
        with:
          file-path: date.json
          commit-msg: "Actualización automática de date.json"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update clasificaciones.json
        uses: test-room-7/action-update-file@v1
        with:
          file-path: clasificaciones.json
          commit-msg: "Actualización automática de clasificaciones.json"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update partidos.json
        uses: test-room-7/action-update-file@v1
        with:
          file-path: partidos.json
          commit-msg: "Actualización automática de partidos.json"
          github-token: ${{ secrets.GITHUB_TOKEN }}
